baseurl = "https://ricardolonga.github.io/"
languageCode = "pt-br"
title = "Ricardo Longa"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
disqusShortname = "ricardolonga"

[params]
    navbarTitle          = "Ricardo Longa"
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    viewMorePostLink     = "/post/"

    categoriesByCount    = true
    includeReadingTime   = true
    loadFavicon          = false
    faviconVersion       = ""
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

[params.intro]
    header    = "Ricardo Longa"
    paragraph = "Comodismo é o pior investimento a longo prazo. (Ricardo Longa)"
    about     = "I'm an Java (Android) and Golang (backend) developer."

[params.intro.pic]
    src       = "/images/avatar.png"
    circle    = false
    imperfect = false
    width     = ""
    alt       = "Ricardo Longa"

[params.postAmount]
    sidebar = 2

[[menu.main]]
    name = "Posts"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[social]
    github          = "ricardolonga"
    linkedin        = "ricardolonga"
    slideshare      = "ricardolonga"
    twitter         = "ricardolonga"